### ISSUE TITLE
`sleep()` like function

### ISSUE THREAD

**Issue by Moosems** [sa-/mo-time#3]
Is a function similar to `time.sleep()` planned?

**Comment by sa-** [comment]
Mojo already implements this: https://docs.modular.com/mojo/stdlib/time/time.html#sleep

The current projects scope is more on the side of time as non-programmers think of it so anything to with sleeping threads, execution/cpu time etc would not be in scope here

**Comment by sa-** [comment]
Congrats on being the first issue btw :D
